
#[derive(Deserialize, Debug)]
pub struct TraceEvent {
    pub event: String,
    pub host: Option<String>,
    pub time: u64,
    pub pid: i32,
    pub ppid: i32,
    pub tid: i32,
    pub uid: i32,
    pub exec: Option<String>,
    pub cmdline: Option<String>,
    pub upath1: Option<String>,
    pub upath2: Option<String>,
    pub fd: Option<i32>,
    pub flags: Option<i32>,
    pub fdpath: Option<String>,
    pub subjprocuuid: String,
    pub subjthruuid: String,
    pub arg_objuuid1: Option<String>,
    pub arg_objuuid2: Option<String>,
    pub ret_objuuid1: Option<String>,
    pub ret_objuuid2: Option<String>,
    pub retval: i32,
}

#[derive(Deserialize, Debug)]
struct TraceEventIdeal {
    event: String,
    host: Option<String>,
    time: u64,
    pid: i32,
    ppid: i32,
    tid: i32,
    uid: i32,
    exec: Option<String>,
    cmdline: Option<String>,
    upath1: Option<String>,
    upath2: Option<String>,
    fd: Option<i32>,
    flags: Option<i32>,
    fdpath: Option<String>,
    subjprocuuid: [i64; 2],
    subjthruuid: [i64; 2],
    arg_objuuid1: Option<[i64; 2]>,
    arg_objuuid2: Option<[i64; 2]>,
    ret_objuuid1: Option<[i64; 2]>,
    ret_objuuid2: Option<[i64; 2]>,
    retval: i32,
}
